### ISSUE TITLE
Update multi-gpu to support newer keras versions

### ISSUE THREAD

**Issue by jouniluoma** [jouniluoma/bert-ner-cmv#1]
The code was written on older version of keras and should be updated. Multi-gpu is not properly working at the moment.

**Comment by AnttiKarlsson** [comment]
Btw, would it be possible to include a requirements.txt ? That'd make it easier to setup a venv for this.

**Comment by jouniluoma** [comment]
I should check this. Been busy elsewhere for a while

**Comment by AchmadAth** [comment]
Currently I get this error problem from multi-gpu things, can you provide the requirement.txt please?
