### ISSUE TITLE
Replicating results on CoNLl03

### ISSUE THREAD

**Issue by Dimiftb** [jouniluoma/bert-ner-cmv#2]
Hi, 

Thank you very much for your model. I was wondering how can I go about replicating your results on the CoNLl dataset? Thanks.

**Comment by jouniluoma** [comment]
Hi,
For CONLL'03 English, you can download the BERT Large WWM Cased from https://storage.googleapis.com/bert_models/2019_05_30/wwm_cased_L-24_H-1024_A-16.zip
I have used IOB2 encoded (every entity starts with B-TAG) and used the -DOCSTART- tokens to prepare documentwise input samples for CMV method. 
I got the best results with maximum sequence length of 512, LR 2e-5, BS 2, Epochs 3 and using concatenated train & dev set for training the final model.

**Comment by Dimiftb** [comment]
HI @jouniluoma, 

I appreciate your help, however I might need a little more detail if possible? Where should I put the model when I extract it from the zip? In the `models` folder? 

Also, where can I acquire the specific dataset you used to get the best results? Can you provide a link where I can download it? If not can you provide specific instructions how to transform the original CoNLl `train.txt, testa.txt, testb.txt` into what you used to get the best results?

Also, what is the command to run the model for evaluation? is it just `python ner.py`? Can I pass the hyper parameters you've specified to this? If yes, how? 

Thanks for your help.

**Comment by jouniluoma** [comment]
Please check the files in scripts folder e.g. run-turku-ner.sh on how to
use the code.  I do not have any specific download link for data, but you
can use linux tools to convert the data to utf-8 and then you may have to
convert also the mentions to IOB2 format. You should note that this is
research code provided as is, not a product with customer support. I hope
this helps you to run the code.

**Comment by Dimiftb** [comment]
That's okay, I can easily choose another model for baseline. Appreciate the help. Closing this now.
