### ISSUE TITLE
Why do you use bert tokenization.py instead of keras-bert tokenizer.py?

### ISSUE THREAD

**Issue by pinesnow72** [jouniluoma/bert-ner-cmv#3]
Great thanks to opening your repository.
You are using keras-bert, instead of original bert but using original bert tokenizer.
I am curious why you are not using keras-bert tokenizer.
Does keras-bert tokenizer give different (i.e., bad) results?

**Comment by jouniluoma** [comment]
If I remember correctly (I wrote that part of code 2 years ago) there were some tokenization corner cases, but nothing major. I think the main reason was just that keras-bert tokenizer adds [CLS] and [SEP] tokens which I did not want to be there, as wanted to do some extra processing and would have needed to strip those away.
